### ISSUE TITLE
Uncaught TypeError: tinycolor(...).isValid is not a function

### ISSUE THREAD

**Issue by katsutosh** [ckpack/vue-color#10]
Hey

I use version 1.1.7 (latest) of this package and the Sketch picker.
And vue 3.2.29
If i change the value of the Hex Input field, its throw a error  (on your demo page too) and the color doesnt change

``` 
On my site:
Uncaught TypeError: tinycolor(...).isValid is not a function
    at Proxy.isValidHex (color.js?0885:97:1)
    at Proxy.inputChange (index.js?2314:78:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?d2dd:155:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?d2dd:164:1)
    at emit$1 (runtime-core.esm-bundler.js?d2dd:718:1)
    at Proxy.handleChange (index.js?02ca:51:1)
    at Proxy.update (index.js?02ca:43:1)
    at onInput._cache.<computed>._cache.<computed> (index.js?02ca:102:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?d2dd:155:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?d2dd:164:1)
```

```
on your demo page
TypeError: z(...).isValid is not a function
    at Proxy.isValidHex (index.min.js:1:18351)
    at Proxy.inputChange (index.min.js:1:51514)
    at It (vue.global.prod.js:1:14065)
    at Bt (vue.global.prod.js:1:14143)
    at un (vue.global.prod.js:1:16040)
    at Proxy.handleChange (index.min.js:1:19188)
    at Proxy.update (index.min.js:1:19063)
    at t.createElementBlock.t.withDirectives.t.createElementVNode.onInput.a.<computed>.a.<computed> (index.min.js:1:19996)
    at It (vue.global.prod.js:1:14065)
    at Bt (vue.global.prod.js:1:14143)
```

**Comment by ckvv** [comment]
@katsutosh 
Fix in `v1.1.8`
